########################
# Customize the test machine
########################
machine:

  # Set the timezeone - any value from /usr/share/zoneinfo/ is valid here
  timezone:
    America/Los_Angeles

  # Version of ruby to use
  ruby:
    version:
      2.2.4
